import { GeistMono } from 'geist/font/mono'
import { GeistSans } from 'geist/font/sans'

import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/blocks/theme-provider';
import { TailwindIndicator } from '@/components/blocks/tailwind-indicator';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className={cn('h-screen bg-background font-sans antialiased',
        GeistMono.variable, GeistSans.variable,
      )}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className={cn('relative flex min-h-screen flex-col')}>
            <div className={'flex-1'}>{children}</div>
            <Toaster />
          </main>
          <TailwindIndicator />
        </ThemeProvider>
      </body>
    </html>
  );
}
